language: node_js
node_js:
  - "node"
  - "10"
  - "lts/carbon"
install:
  - npm install
before_script:
  - npm update
  - npm run build
script:
  - npm run cov
after_success:
  - npm install codecov -g
  - codecov
cache:
  directories:
    - node_modules
